steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/group-helper', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/group-helper']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'group-helper',
      '--image', 'gcr.io/$PROJECT_ID/group-helper',
      '--platform', 'managed',
      '--region', 'europe-west6',
      '--allow-unauthenticated',
      '--set-env-vars', 'GCP_PROJECT=$PROJECT_ID',
      '--min-instances', '1'
    ]

images:
  - 'gcr.io/$PROJECT_ID/group-helper'