steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
    args: [
      'compute', 'instances', 'create', 'auto-group-app-vm',
      '--zone', 'europe-west6-b',
      '--machine-type', 'e2-micro',
      '--metadata-from-file', 'startup-script=startup-script_vm.sh',
      '--tags', 'http-server,https-server',
      '--scopes', 'https://www.googleapis.com/auth/cloud-platform'
    ]