steps:
  - name: 'python:3.11'  # Use the Python runtime to install dependencies
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        PROJECT_ID=$(gcloud config get-value project)
        export GCP_PROJECT=$PROJECT_ID
        gcloud app deploy ./app.yaml --project=$PROJECT_ID
