steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'compute', 'instances', 'create', 'group-helper-vm',
      '--zone', 'europe-west6-b',
      '--machine-type', 'n1-standard-1',
      '--metadata-from-file', 'startup-script=startup-script.sh',
      '--tags', 'http-server,https-server'
    ]